# Generated by Django 5.2.10 on 2026-06-04 21:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_favorite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Üzenet')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozás ideje')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='listings.property', verbose_name='Ingatlan')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Fogadó')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_contact_messages', to=settings.AUTH_USER_MODEL, verbose_name='Küldő')),
            ],
            options={
                'verbose_name': 'Kapcsolatfelvételi üzenet',
                'verbose_name_plural': 'Kapcsolatfelvételi üzenetek',
                'ordering': ['-created_at'],
            },
        ),
    ]
