# Generated by Django 5.2.10 on 2026-06-04 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/gallery/', verbose_name='Galériakép')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés ideje')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='listings.property', verbose_name='Ingatlan')),
            ],
            options={
                'verbose_name': 'Ingatlan galériakép',
                'verbose_name_plural': 'Ingatlan galériaképek',
                'ordering': ['created_at'],
            },
        ),
    ]
